baseURL: "https://davidinsider.com/"
title: Home
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-C82WSJW7GT

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # To enable google analytics, opengraph, twitter-cards and schema.
  description: "Explore insightful blog posts and discover content based on a wide range of emerging technologies, programming, networking, and cybersecurity."
  keywords: [
      Portfolio,
      Site,
      Blog,
      Cloud,
      AWS,
      Artificial Intelligence,
      Machine Learning,
      GCP,
      Azure,
      Blogging,
      Technology,
      Cybersecurity,
      Networking,
      Programming,
      Software,
      Engineering,
      DevOps,
      DevSecOps,
      Cloud Security
      David,
      Cepeda,
      David Cepeda,
    ]
  defaultTheme: dark
  disableThemeToggle: false
  showDate: true
  showDateUpdated: true
  showHeadingAnchors: true
  showPagination: true
  showReadingTime: true
  showTableOfContents: true
  showTaxonomies: false
  showWordCount: false
  showSummary: false
  sharingLinks: true
  ShowShareButtons: false
  ShowReadingTime: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: true
  images: ["logo.svg"]
  comments: true

  profileMode:
    enabled: false
    title: Hi \U0001F32E
    imageUrl: "img/profile.jpg"
    imageTitle: Sagar Chamling's Photo
    imageWidth: 250
    imageHeight: 250
    subtitle: "A passionate full-stack software engineer and cyber security enthusiast. Explore my recent blog articles, where I write about my works, share valuable insights on emerging technologies, programming, networking and cybersecurity in a company accepted best practices and standards. Stay tuned for more!."
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags
      - name: "#tech"
        url: blogs/tech

  homeInfoParams:
    enabled: true
    imageUrl: "profile.jpg"
    imageTitle: David Cepeda's Photo
    imageWidth: 250
    imageHeight: 250

  socialIcons:
    - name: twitter
      url: "https://twitter.com/davidsvida784"
    - name: linkedin
      url: "https://www.linkedin.com/in/davidcepeda05/"
    - name: ycombinator
      url: "https://news.ycombinator.com/user?id=davidsvida"
    - name: other 
      url: "https://docs.google.com/document/d/1i2J1ep5MFIYqG-mAg1iILxIVgpexzTRe"
    - name: spotify
      url: "https://open.spotify.com/user/dcepeda784"





  label:
    text: "cham11ng's blog"
    # icon: "logo.png"
    # iconHeight: 35

  # analytics:
  # google:
  # SiteVerificationTag: "abc"

  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    android_chrome192x192: "android-chrome-192x192.png"
    android_chrome512x512: "android-chrome-512x512.png"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
