name: Deploy Hugo Site to AWS

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.119.0
      BUCKET: davidinsider.com # Replace with your AWS S3 bucket name
      REGION: eu-west-2 # Replace with your AWS region
      DIST_ID: E2ROCM2HNIE676 # Replace with your AWS CloudFront distribution ID
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Build with Hugo
        run: hugo --gc --minify

      - name: Deploy to AWS S3
        run: aws s3 sync ./public s3://${{ env.BUCKET }} --delete

      - name: Invalidate AWS CloudFront Distribution
        run: aws cloudfront create-invalidation --distribution-id ${{ env.DIST_ID }} --paths "/*"
